- hosts: all
  become: yes
  tasks:
    - name: Add multiple host entries to /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: |
          192.168.0.1 redos
          192.168.0.2 alt
          192.168.0.3 astra
        marker: "# {mark} ANSIBLE-MANAGED HOSTS"
        insertafter: EOF
        owner: root
        group: root
        mode: '0644'
