---
- name: Configure network interfaces and NAT
  hosts: astra
  become: yes
  tasks:

    # Настройка внутреннего интерфейса eth1
    - name: Configure internal interface (eth1)
      community.general.nmcli:
        conn_name: "eth1"
        ifname: "eth1"
        type: "ethernet"
        ip4: "192.168.0.3/24"
        gw4: "192.168.0.1"
        state: present
