---
- name: Configure network interfaces and NAT
  hosts: alt
  become: yes
  tasks:

    # Настройка внутреннего интерфейса eth1
    - name: Configure internal interface (eth1)
      community.general.nmcli:
        conn_name: "eno0s8"
        ifname: "enp0s8"
        type: "ethernet"
        ip4: "192.168.0.2/24"
        gw4: "192.168.0.1"
        state: present
